apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "registry-image-pvc"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.source: "registry"
    cdi.kubevirt.io/storage.import.endpoint: "docker://kubevirt/fedora-cloud-registry-disk-demo"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Optional: Set the storage class or omit to accept the default
  storageClassName: local
